Fix undefined print_ error
On newer versions of Node, I get this error:

    TypeError: this.print_ is not a function

I believe this is because Node has deprecated util.print in favor of
console.log